import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
theme: {
  extend: {
colors: {
        contribution: {
            none: '#161b22',
            'first-quartile': '#0e4429',
            'second-quartile': '#006d32',
            'third-quartile': '#26a641',
            'fourth-quartile': '#39d353',
        },
        git: {
            'dark-bg-header': '#0d1117',
            'error-text': '#f85149',
            'dark-bg-primary': '#0d1117',
            'dark-bg-secondary': '#010409',
        },
        // Existing colors start here
      'gh-dark-bg-primary': '#0d1117',
      'gh-dark-border': '#30363d',
      'gh-dark-bg-secondary': '#161b22',
    },
  },
    extend: {
      colors: {
        language: {
          TypeScript: '#3178c6',
          JavaScript: '#f1e05a',
          Python: '#3572A5',
          Java: '#b07219',
          'C++': '#f34b7d',
          C: '#555555',
          'C#': '#178600',
          Ruby: '#701516',
          Go: '#00ADD8',
          Rust: '#dea584',
          HTML: '#e34c26',
          CSS: '#563d7c',
          PHP: '#4F5D95',
          Vue: '#41b883',
          Swift: '#F05138',
          Kotlin: '#A97BFF',
          Dart: '#00B4AB',
          Shell: '#89e051',
          ObjectiveC: '#438eff',
          Scala: '#c22d40',
          Elixir: '#6e4a7e',
          Clojure: '#db5855',
          Haskell: '#5e5086',
          Lua: '#000080',
          Perl: '#0298c3',
          R: '#198CE7',
          Svelte: '#ff3e00',
          HolyC: '#ffef28',
          default: '#8b949e'
        },
        'gh-dark': '#0D1117',
        'gh-canvas': '#161B22',
        'gh-border': '#30363D',
        'gh-green': '#238636',
        'gh-green-light': '#2EA043',
        'gh-blue': '#1F6FEB',
        'gh-text': '#E6EDF3',
        'repo-card-bg': '#0d1117',
        'repo-card-hover-bg': '#161b22',
        'gh-muted': '#8B949E',
        'gh-green-glow': 'rgba(35, 134, 54, 0.15)',
        'git-green-hover': '#2ea043',
        'git-error': '#f85149',
        git: {
          scoreGreen: '#2ea043',
          bg: "var(--bg)",
          card: "var(--card)",
          border: "var(--border)",
          green: "var(--green)",
          accent: "var(--accent)",
          text: "var(--text)",
          muted: "var(--muted)",
          notification: "var(--notification)",
          hover: "var(--hover)",
          'tab-active-border': '#f78166',
          'tab-count-bg': '#30363d',
          contribution: {
            0: "#161B22",
            1: "#0e4429",
            2: "#006d32",
            3: "#26a641",
            4: "#39d353",
          },
        },
        githubBlue: '#2f81f7',
        githubDarkBg: '#161b22',
        'star-active': '#e3b341',
        'timeline-border-dark': '#0d1117',
        'timeline-bg-dark': '#161b22',
        'timeline-icon-default': '#8b949e',
        'timeline-divider': '#30363d',
        'timeline-progress-blue': '#1f6feb',
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Noto Sans",
          "Helvetica",
          "Arial",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
        ],
        mono: [
          '"SFMono-Regular"',
          "Consolas",
          '"Liberation Mono"',
          "Menlo",
          "monospace",
        ],
      },
    },
  },
  plugins: [],
};

export default config;
